#CREATE DATABASE
CREATE DATABASE birds_db;
USE birds_db;

#ADD GENERIC NAME COLUMNS TO bird_strikes, bld strikes 
#USE UPDATE QUERIES TO FILL IN GENERIC NAMES USING WILDCARDS
#UPDATE AIRPORT CODES IN bird_strikes
#SET PRIMARY AND FOREIGN KEYS
# PERFORM JOINS